import "./globals.css";
import { AlertDialogProvider } from "@/components/element/context/alert-dialog-context";
import AlertDialog from "@/components/element/dialog/alert-dialog";
import "react-datepicker/dist/react-datepicker.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getCsrfToken() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/sanctum/csrf-cookie`, {
    method: 'GET',
    credentials: 'include',  // Pastikan cookie dikirim
  });
  return res.ok;
}

export default async function RootLayout({children}: { children: React.ReactNode;}) {
  await getCsrfToken();

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AlertDialogProvider>
          {children}
          <AlertDialog />
        </AlertDialogProvider>
      </body>
    </html>
  );
}
